version: "3"
services:
  web:
    image: hiteshbal91/node-mongo
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "3000:6000"
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet      
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet      
networks:
  webnet: